// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://www.ebutilities.at/schemata/customerprocesses/consumptionrecord/01p40
package cp

import (
	"encoding/xml"
	"github.com/WattWiseAt/ebutilities/models/customerprocesses/consumptionrecord/ct"
)

// Element
type ConsumptionRecord struct {
	XMLName xml.Name `xml:"ConsumptionRecord"`

	MarketParticipantDirectory MarketParticipantDirectory `xml:"MarketParticipantDirectory"`

	ProcessDirectory ProcessDirectory `xml:"ProcessDirectory"`
}

// XSD ComplexType declarations

type MarketParticipantDirectory struct {
	XMLName xml.Name

	SchemaVersion string `xml:"SchemaVersion,attr"`

	DocumentMode ct.DocumentMode `xml:"DocumentMode,attr"`

	Duplicate bool `xml:"Duplicate,attr"`

	MessageCode ct.MessageCode `xml:"MessageCode"`

	RoutingHeader ct.RoutingHeader `xml:"RoutingHeader"`

	Sector ct.Sector `xml:"Sector"`
}

type ProcessDirectory struct {
	XMLName xml.Name

	Ecid *ct.MeteringPoint `xml:"ECID"`

	DeliveryPoint *ct.MessageAddress `xml:"DeliveryPoint"`

	Energy []Energy `xml:"Energy"`

	MessageId ct.GroupingId `xml:"MessageId"`

	ConversationId ct.GroupingId `xml:"ConversationId"`

	ProcessDate string `xml:"ProcessDate"`

	MeteringPoint ct.MeteringPoint `xml:"MeteringPoint"`
}

type Energy struct {
	XMLName xml.Name

	MeteringReason *MeteringReason `xml:"MeteringReason"`

	MeteringPeriodStart DateTimeU `xml:"MeteringPeriodStart"`

	MeteringPeriodEnd DateTimeU `xml:"MeteringPeriodEnd"`

	MeteringIntervall MeteringIntervall `xml:"MeteringIntervall"`

	NumberOfMeteringIntervall int64 `xml:"NumberOfMeteringIntervall"`

	EnergyData []EnergyData `xml:"EnergyData"`
}

type EnergyData struct {
	XMLName xml.Name

	MeterCode string `xml:"MeterCode,attr"`

	Uom Uomtype `xml:"UOM,attr"`

	Ep []EnergyPosition `xml:",any"`
}

type EnergyPosition struct {
	XMLName xml.Name

	Dtf DateTimeU `xml:"DTF"`

	Dtt DateTimeU `xml:"DTT"`

	Mm MeteringMethod `xml:"MM"`

	Bq BillingQuantity `xml:"BQ"`
}

// XSD SimpleType declarations

type BillingQuantity float64

type Competence string

type ConsumptionRecordMessageCode string

const ConsumptionRecordMessageCodeDatenMsg ConsumptionRecordMessageCode = "DATEN_MSG"

type ConsumptionRecordVersion string

const ConsumptionRecordVersion0140 ConsumptionRecordVersion = "01.40"

type Email string

type Fax string

type MeteringIntervall string

const MeteringIntervallQh MeteringIntervall = "QH"

const MeteringIntervallH MeteringIntervall = "H"

const MeteringIntervallD MeteringIntervall = "D"

const MeteringIntervallV MeteringIntervall = "V"

type MeteringMethod string

const MeteringMethod01 MeteringMethod = "01"

const MeteringMethod02 MeteringMethod = "02"

const MeteringMethod03 MeteringMethod = "03"

const MeteringMethod04 MeteringMethod = "04"

const MeteringMethod05 MeteringMethod = "05"

const MeteringMethodL1 MeteringMethod = "L1"

const MeteringMethodL2 MeteringMethod = "L2"

const MeteringMethodL3 MeteringMethod = "L3"

type MeteringReason string

const MeteringReason00 MeteringReason = "00"

const MeteringReason01 MeteringReason = "01"

const MeteringReason02 MeteringReason = "02"

const MeteringReason03 MeteringReason = "03"

const MeteringReason04 MeteringReason = "04"

const MeteringReason05 MeteringReason = "05"

type Name string

type Phone string

type ReferenceNumber string

type Uomtype string

const UomtypeProz Uomtype = "PROZ"

const UomtypeCels Uomtype = "CELS"

const UomtypePce Uomtype = "PCE"

const UomtypeEur Uomtype = "EUR"

const UomtypeMb Uomtype = "MB"

const UomtypeGb Uomtype = "GB"

const UomtypeTb Uomtype = "TB"

const UomtypeH Uomtype = "H"

const UomtypeTag Uomtype = "TAG"

const UomtypeMin Uomtype = "MIN"

const UomtypeMon Uomtype = "MON"

const UomtypeKvarh Uomtype = "KVARH"

const UomtypeMvarh Uomtype = "MVARH"

const UomtypeKwt Uomtype = "KWT"

const UomtypeMwt Uomtype = "MWT"

const UomtypeGwt Uomtype = "GWT"

const UomtypeKwh Uomtype = "KWH"

const UomtypeMwh Uomtype = "MWH"

const UomtypeGwh Uomtype = "GWH"

const UomtypeLe Uomtype = "LE"

const UomtypeM2 Uomtype = "M2"

const UomtypeM3 Uomtype = "M3"

const UomtypeBm3 Uomtype = "BM3"

const UomtypeNm3 Uomtype = "NM3"

const UomtypeBm3H Uomtype = "BM3H"

const UomtypeNm3H Uomtype = "NM3H"

const UomtypeKwhh Uomtype = "KWHH"

const UomtypePau Uomtype = "PAU"

type DateTimeS string

type DateTimeU string

type DocumentMode string

const DocumentModeProd DocumentMode = "PROD"

const DocumentModeSimu DocumentMode = "SIMU"

type GroupingId string

type MessageAddress string

type MessageCode string

type MeteringPoint string
