// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://www.ebutilities.at/schemata/customerprocesses/ecmplist/01p10
package cp

import (
	"encoding/xml"
	"github.com/colibrie-eu/ebutilities/models/customerprocesses/ecmplist/ct"
)

// Element
type Ecmplist struct {
	XMLName xml.Name `xml:"ECMPList"`

	MarketParticipantDirectory MarketParticipantDirectory `xml:"MarketParticipantDirectory"`

	ProcessDirectory ProcessDirectory `xml:"ProcessDirectory"`
}

// XSD ComplexType declarations

type MarketParticipantDirectory struct {
	XMLName xml.Name

	SchemaVersion string `xml:"SchemaVersion,attr"`

	DocumentMode ct.DocumentMode `xml:"DocumentMode,attr"`

	Duplicate bool `xml:"Duplicate,attr"`

	MessageCode ct.MessageCode `xml:"MessageCode"`

	RoutingHeader ct.RoutingHeader `xml:"RoutingHeader"`

	Sector ct.Sector `xml:"Sector"`
}

type ProcessDirectory struct {
	XMLName xml.Name

	MessageId ct.GroupingId `xml:"MessageId"`

	ConversationId ct.GroupingId `xml:"ConversationId"`

	ProcessDate string `xml:"ProcessDate"`

	Ecid ct.MeteringPoint `xml:"ECID"`

	Ectype Ectype `xml:"ECType"`

	EcdisModel EcdisModel `xml:"ECDisModel"`

	MplistData []MplistData `xml:"MPListData"`
}

type MplistData struct {
	XMLName xml.Name

	MeteringPoint ct.MeteringPoint `xml:"MeteringPoint"`

	ConsentId *ct.GroupingId `xml:"ConsentId"`

	MptimeData []MptimeData `xml:"MPTimeData"`
}

type MptimeData struct {
	XMLName xml.Name

	DateFrom string `xml:"DateFrom"`

	DateTo string `xml:"DateTo"`

	EnergyDirection EnergyDirection `xml:"EnergyDirection"`

	EcpartFact EcpartFact `xml:"ECPartFact"`

	PlantCategory *PlantCategory `xml:"PlantCategory"`

	DateActivate string `xml:"DateActivate"`

	DateDeactivate string `xml:"DateDeactivate"`

	Ecshare *Ecshare `xml:"ECShare"`

	EcshC []ShareCalc `xml:"ECShC"`
}

type ShareCalc struct {
	XMLName xml.Name

	DateFrom string `xml:"DateFrom"`

	DateTo string `xml:"DateTo"`

	EcshareCalc Ecshare `xml:"ECShareCalc"`
}

// XSD SimpleType declarations

type EcdisModel string

const EcdisModelD EcdisModel = "D"

const EcdisModelS EcdisModel = "S"

type Ecshare float64

type Ectype string

const EctypeGc Ectype = "GC"

const EctypeRcR Ectype = "RC_R"

const EctypeRcL Ectype = "RC_L"

const EctypeCc Ectype = "CC"

type EnergyDirection string

const EnergyDirectionConsumption EnergyDirection = "CONSUMPTION"

const EnergyDirectionGeneration EnergyDirection = "GENERATION"

type EcpartFact float64

type PlantCategory string
