// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://www.ebutilities.at/schemata/customerconsent/cmrevoke/01p00
package cp

import (
	"encoding/xml"
	"github.com/WattWiseAt/ebutilities/models/customerconsent/cmrevoke/ct"
)

// Element
type Cmrevoke struct {
	XMLName xml.Name `xml:"CMRevoke"`

	MarketParticipantDirectory MarketParticipantDirectory `xml:"MarketParticipantDirectory"`

	ProcessDirectory ProcessDirectory `xml:"ProcessDirectory"`
}

// XSD ComplexType declarations

type MarketParticipantDirectory struct {
	XMLName xml.Name

	SchemaVersion string `xml:"SchemaVersion,attr"`

	DocumentMode ct.DocumentMode `xml:"DocumentMode,attr"`

	Duplicate bool `xml:"Duplicate,attr"`

	MessageCode string `xml:"MessageCode"`

	RoutingHeader ct.RoutingHeader `xml:"RoutingHeader"`

	Sector ct.Sector `xml:"Sector"`
}

type ProcessDirectory struct {
	XMLName xml.Name

	ConsentId ct.GroupingId `xml:"ConsentId"`

	MeteringPoint ct.MeteringPoint `xml:"MeteringPoint"`

	ConsentEnd string `xml:"ConsentEnd"`

	Reason *ReasonType `xml:"Reason"`

	MessageId ct.GroupingId `xml:"MessageId"`

	ConversationId ct.GroupingId `xml:"ConversationId"`
}

// XSD SimpleType declarations

type ReasonType string
