---
name: Release

on:
  push:
    branches: [ dev ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ dev ]

permissions:
 contents: write

jobs:
  audit:
    uses: colibrie-eu/github-actions/.github/workflows/release.yaml@main
